### ISSUE TITLE
useDomPurify

### ISSUE THREAD

**Issue by simmons8616** [ecomfe/react-hooks#13]
您好～

可不可以加一个新的hook，**用于处理html字符串并防止XSS攻击**

下面的实现会带来一个问题：引入[dompurify](https://github.com/cure53/DOMPurify)这个第三方的dependencies，如果自己去实现[dompurify](https://github.com/cure53/DOMPurify)这个确实有些成本，不知您这边有什么好的建议吗？
```ts
import {useMemo} from 'react';
import createDomPurify from 'dompurify';

const domPurify = createDomPurify(window);

const useDomPurify = function (html: string = ''): string {
    return useMemo<string>(
        function () {
            return domPurify.sanitize(html);
        },
        [html]
    );
};

export default useDomPurify;
```

**Comment by otakustay** [comment]
我觉得有2个问题需要讨论下：

1. React默认是有XSS能力的，你是否希望这个东西仅用在`dangerouslySetInnerHTML`上？
2. 这个hook它的参数是字符串，返回值也是字符串。但是在相等的`===`比较上，字符串是不存在“内容相同但引用不同”这个问题的，也即是说，在这件事上使用`useMemo`除了某些时候会有一点性能收益以外，对程序的正确性、组件的render次数是没有效果的，那么理论上它不需要是一个hook

**Comment by Justineo** [comment]
这个为啥不是直接引一个 util function 调用一下就好了……

**Comment by otakustay** [comment]
这个事情吧，其实用一个带容量的cache函数是最容易实现的，可以完全和React无关

**Comment by simmons8616** [comment]
> 这个事情吧，其实用一个带容量的cache函数是最容易实现的，可以完全和React无关

明白了，可以完全和React解耦，独立出来，为了追求性能可以用cache函数做缓存，感谢～

**Comment by otakustay** [comment]
好，那我先关Issue了~对hook有想法欢迎随时提需求和讨论

**Comment by simmons8616** [comment]
> 好，那我先关Issue了~对hook有想法欢迎随时提需求和讨论

好的，我再思考思考新的feature~
