### ISSUE TITLE
useArray的remove方法无法用于非基础类型

### ISSUE THREAD

**Issue by otakustay** [ecomfe/react-hooks#40]
```js
const [items, {remove}] = useArray(dataSource); // dataSource为对象数组
remove(someItem);
```

以上代码会失败，因为在`immer`的作用下都是`Proxy`，没办法引用判断相等

**Comment by otakustay** [comment]
误判，非Bug

**Comment by qiaoyuwen** [comment]
我现在在使用过程中也遇到了这个问题，这是测试的demo：https://codesandbox.io/s/heuristic-snowflake-behjz
在文档中没有找到使用示例，请问应该怎么来正确使用useArray的remove方法呢？

**Comment by otakustay** [comment]
@qiaoyuwen 已确认是BUG，原因是与`immer`兼容问题，修复中
