### ISSUE TITLE
[Feature] useDebouncedCallback add 'cleanUp' function as params 

### ISSUE THREAD

**Issue by susiwen8** [ecomfe/react-hooks#51]
I have noticed that `useDebouncedCallback` doesn't have independent 'cleanUp' function. It uses `clear` function which should attach to `debouncedCallback`. Also I have notice there is unused interface `DebouncedFunction`, it seems to me that `useDebouncedCallback` had some plan for it.

So I propose something like this
```typescript
function useDebouncedCallback<C extends Function>(
    options: {
        callback: C;
        clear?: () => void;
    },
    wait: number
): C
```

If I miss something, or this was intentional, just give a heads up. If you agreed, I'll be happy to make a PR for it.

Thanks

**Comment by otakustay** [comment]
I have seen cases where `debounce` **returnes** a `clear` function which would cancel pending executions, but I'm confused about your `clear` function **passed** to `useDebouncedCallback`, when should `clear` be called, what could happen on its execution, maybe you can provide some real world use cases to clarify the functionality of clear

**Comment by susiwen8** [comment]
> I have seen cases where `debounce` **returnes** a `clear` function which would cancel pending executions,

I see. that is where I have missed.
