### ISSUE TITLE
doesn't work on IE11

### ISSUE THREAD

**Issue by sinchang** [ecomfe/react-hooks#65]
![image](https://user-images.githubusercontent.com/3297859/100842324-a3fd2a00-34b3-11eb-9d2c-43d5eed10850.png)

seems the compiled code doesn't work on IE 11.

**Comment by sinchang** [comment]
compilerOptions target: ES2015

![image](https://user-images.githubusercontent.com/3297859/100843246-0b67a980-34b5-11eb-89ef-bca7d1e3c140.png)

compilerOptions target: ES5

![image](https://user-images.githubusercontent.com/3297859/100843304-20dcd380-34b5-11eb-9b7b-b1d4793f0163.png)

so quick solution is change the target to `ES5`

Ref: https://www.meziantou.net/which-version-of-ecmascript-should-i-use-in-the-typescript-configuration.htm#select-your-target-j

**Comment by otakustay** [comment]
Yes, we have target set to `ES2015` by design to produce minimum code size and to be compatible with ES modules.

We will discuss this in our team, I don't have a good expectation to change it to `ES5`, for now I'd recommended you to process these packages via babel
