### ISSUE TITLE
useOnScreenCallback 返回的 ref 不能获取 ref.current 么

### ISSUE THREAD

**Issue by feibinyang** [ecomfe/react-hooks#70]
问题：使用 `useOnScreenCallback` 这个 hook 返回的 ref，赋值给 DOM 元素后，ref.current 不能获取到 DOM。但在使用中会有需要获取这个 DOM 进行操作的情景（比如 add/remove classList 来显示动画）；

期望：希望赋值完 ref={ref} 后，ref.current 可以获取 DOM 结构，这样可以在 callback 里直接进行后续操作。

参考 demo：https://codesandbox.io/s/heuristic-haslett-s1qs8?fontsize=14&hidenavigation=1&theme=dark

**Comment by feibinyang** [comment]
忘记有 entry.target  了

**Comment by otakustay** [comment]
顺便提一下，类似其它需要这种功能的场景，也可以这样：

```js
const elementRef = useRef(null);
const registerOnScreen = useOnScreenCallback(...);
const ref = useMergedRef([elementRef, registerOnScreen]);

<div ref={ref} />
```

参考：https://ecomfe.github.io/react-hooks/#/hook/merged-ref/use-merged-ref
