### ISSUE TITLE
allow useDebouncedCallback option `leading` or `immediate`

### ISSUE THREAD

**Issue by nick-ChenZe** [ecomfe/react-hooks#76]
在一些场景，debouncedCalback 即使只触发一次，也会带来 wait 时间的延迟，debounce 的 immediate 属性可以开放出来

![image](https://user-images.githubusercontent.com/12672355/113403341-0ec65f80-93d9-11eb-825c-e1d0c7cedf55.png)

**Comment by otakustay** [comment]
支持，你PR还是我来？
