### ISSUE TITLE
Can't find @huse/router

### ISSUE THREAD

**Issue by cheungww** [ecomfe/react-hooks#87]
my huse version is 2.0.1 (latest)

![image](https://user-images.githubusercontent.com/39025167/117531551-8b221300-b015-11eb-9abc-0f0503bab0fc.png)
![image](https://user-images.githubusercontent.com/39025167/117531433-046d3600-b015-11eb-91bb-e1cfaa01f4e4.png)
![image](https://user-images.githubusercontent.com/39025167/117531480-3b434c00-b015-11eb-82eb-582ad28bf847.png)
![image](https://user-images.githubusercontent.com/39025167/117531595-c1f82900-b015-11eb-86dd-08b45903844a.png)

I want to why and how fix it ?

**Comment by otakustay** [comment]
As documented in README, router is not contained in huse package, this is a consideration from the fact that react-router is preparing its 6.x version, it could introduce a breaking change if is included in huse

**Comment by cheungww** [comment]
> As documented in README, router is not contained in huse package, this is a consideration from the fact that react-router is preparing its 6.x version, it could introduce a breaking change if is included in huse

OK. Thx
