### ISSUE TITLE
request in Suspense

### ISSUE THREAD

**Issue by meerkat-morecats** [ecomfe/react-hooks#88]
是否可以增加支持`Suspense`的`useRequset`和`useRequestCallback`，或者在已有的request的基础上增加一个支持suspense的boolean类型的参数。

**Comment by otakustay** [comment]
这么搞是不用的，因为`useRequest`本质是一个本地状态，而`Suspense`在收到`Promise`时会把组件给unmount掉，一但unmount了本地状态就消失了，等请求回来重新挂组件又因为没状态要发请求，你会看到无限请求

`Suspense`能管理数据加载的前提是有一个三层的组件结构：

```
DataCache
  Suspense
    RequestComponent
```

而这不是一个单纯的hook能搞定的

我们有相应的方案，也已经在大面积稳定使用，请参考：https://github.com/ecomfe/react-suspense-boundary
