### ISSUE TITLE
Separate `useAttention` from `usePoll` for more combinations

### ISSUE THREAD

**Issue by 599316527** [ecomfe/react-hooks#97]
https://github.com/ecomfe/react-hooks/blob/8d89a72ea22b6591b9cb226e8378e8ba7cc1e1c2/packages/poll/src/index.ts#L33-L36

Usage:

```
function useAttentiveInterval(task, time) {
     const isActive = useAttention();
     time = isActive ? time : -1;
     useStableInterval(task, time);
}
```

**Comment by otakustay** [comment]
I don't see any case that `usePoll` is insufficient, just don't think it as "fetch a remote response and store it in a state", you can actually pass a void function to it:

```js
usePoll(() => fetch('/ok').catch(() => message.error('System is down'));
```

**Comment by 599316527** [comment]
`usePoll` would call `fetch` at first and every time `fetch` changed additionally while `useIntervel` only calls `fetch` at intervels. So `usePoll` is not proper for my scenario.

https://github.com/ecomfe/react-hooks/blob/8d89a72ea22b6591b9cb226e8378e8ba7cc1e1c2/packages/poll/src/index.ts#L58-L61

**Comment by otakustay** [comment]
Make all interval options the same can force `usePoll` to work as a stable interval, and I'd prefer passing `userAttentionState` as the argument to `fetch` function

**Comment by 599316527** [comment]
There is no way to prevent `usePoll` to call fetch at first now. Otherwise a `leading` option is presented to indicate whether fetch is called at first, `usePoll` would never work as a stable interval.

**Comment by 599316527** [comment]
> it isn't a best practice to initialize `user-attention` inside a component
